### ISSUE TITLE
UpdatePanel throws if CMSVersion doesn't report a Framework version

### ISSUE THREAD

**Issue by OldStarchy** [plastyk/silverstripe-dashboard#107]
The function that gets the current version only checks for the `Framework` module, which is not always returned by `CMSVersion()`. In my case, only `CMS: 3.x-dev` was returned, causing the call to `$updatePanelCache->save` to throw.

https://github.com/plastyk/silverstripe-dashboard/blob/e7f863923bb36da8d53457d769640d4d742d5f1e/code/panels/UpdatePanel.php#L60-L80

The actual module version information returned by `CMSVersion()` is determined by the config setting `SilverStripeVersionProvide` -> `modules` which is set in the CMS to not report the framework version

https://github.com/silverstripe/silverstripe-cms/blob/54047719c0bad22ca64f10f523946206b92eff2e/_config/version.yml#L5-L8

Perhaps there's a more reliable way to get the framework version out of `CMSVerson()` or perhaps just rely on the CMS version as a backup as the CMS and Framework are rarely different versions. Requiring a specific CMS config setting is probably not reasonable.

**Comment by Turnerj** [comment]
I'll try to chat to @3Dgoo about this sometime next week though I agree with what you're suggesting.

**Comment by Turnerj** [comment]
Forgot that this issue was here when I encountered the same issue in SilverStripe 3.7. I implemented a fix (#113) for the 1.x branch which looks at both Framework and CMS values coming back from `CMSVersion()`.

While I noticed the same thing as you about the `SilverStripeVersionProvider` class, I opted for the smaller change of just checking for both CMS and Framework. This method prevented the fix from potentially not being backwards compatible to older versions of SilverStripe (as the version provider class was only merged into SilverStripe mid 2017 and from what I can quickly tell from the tags on the commit, not part of SS 3.6).
