### ISSUE TITLE
Refactor DashboardSearchResultPanel

### ISSUE THREAD

**Issue by 3Dgoo** [plastyk/silverstripe-dashboard#76]
Change `DashboardSearchResultPanel` to work more like this:

```php
class DashboardSearchResultExamplePanel extends DashboardSearchResultPanel
{
    protected $className = 'Example';
    protected $searchFields = array('Title', 'Address', 'Content');
    protected $sort = array('Title' => 'ASC');
    protected $exclusions = array('Title' => 'Mordor');

    public function canView($member = null)
    {
        return parent::canView($member) && Permission::check('CMS_ACCESS_PropertyAdmin') && class_exists('PropertyAdmin');
    }
}
```

**Comment by Turnerj** [comment]
Additional things for us to look at when refactoring the code:
- Building the "where" clause, switching the string building we have currently to make use of PHP's `implode` to glue array items together (this allows us to remove the `$notFirst*` variables and generally make it a little cleaner)
- Moving `raw2sql` from `doDashboardSearch` to the `performSearch` function as otherwise if we ever call `performSearch` directly, we can potentially open up the possibility of SQL injection
- Remove the `$paginatedResults` field and instead use the `$results` field to store the data from `performSearch` (we weren't actually using the `$results` property before and didn't seem much point in having both)
- Add a function that returns the results from the protected `$results` property (this is so if we or someone else wanted to get the result again without re-querying, we could)
- Change last return in `performSearch` to return false or an empty array specifically so the code is a little clearer

I also want to look at changing how we actually get the `$singleSearchResultItem` in `DashboardSearchExtension` but I'm not sure yet on the best approach.
